package com.himanshu.resume_ai_analyzer.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import java.util.List;

/**
 * Data Transfer Object (DTO) representing the structured analysis returned by the AI.
 * This class maps directly to the JSON output generated by the Gemini model.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ResumeAnalysisResponse {

    /** A brief executive summary of the candidate's profile. */
    private String summary;

    /** List of relevant technical or soft skills extracted from the resume. */
    private List<String> keySkills;

    /** List of the candidate's strongest points regarding the target role. */
    private List<String> strengths;

    /** List of missing skills, gaps, or areas for improvement. */
    private List<String> weaknesses;

    /** Actionable advice for the candidate to improve their resume or chances. */
    private List<String> recommendations;

    /** The AI's confidence in its own evaluation (HIGH, MEDIUM, LOW). */
    private String analysisConfidence;

    /** The AI's confidence in its own evaluation (HIGH, MEDIUM, LOW). */
    private int jobFitScore;
}